#include "searchInRotatedArray.cpp"

int main()
{
  /* for class with constructor which takes NO input argument,
   * OR has no constructor defined ( using default constructor
   * generated by compiler):
   *
   * can instantiate the class simply like declaring a primative
   * type:
   */
  Solution s;

  int a[] = {1,3};
  std::cout << s.search(a, 2, 3) << std::endl;

  return 1;
}
